export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL'
export const FETCH_UNSEEN_NOTIFICATIONS_SUCCESS = 'FETCH_UNSEEN_NOTIFICATIONS_SUCCESS'
export const FETCH_UNSEEN_NOTIFICATIONS_FAIL = 'FETCH_UNSEEN_NOTIFICATIONS_FAIL'