export const FETCH_MY_APPLICATIONS_SUCCESS = 'FETCH_MY_APPLICATIONS_SUCCESS'
export const FETCH_MY_APPLICATIONS_FAIL = 'FETCH_MY_APPLICATIONS_FAIL'


// Analytics
export const FETCH_ANALYTICS_DATA_SUCCESS = 'FETCH_ANALYTICS_DATA_SUCCESS'
export const FETCH_ANALYTICS_DATA_FAIL = 'FETCH_ANALYTICS_DATA_FAIL'
export const FETCH_TIME_SPEND_ON_WEBSITE_SUCCESS = 'FETCH_TIME_SPEND_ON_WEBSITE_SUCCESS'
export const FETCH_TIME_SPEND_ON_WEBSITE_FAIL = 'FETCH_TIME_SPEND_ON_WEBSITE_FAIL'