export const FETCH_MY_LISTINGS_SUCCESS = "FETCH_MY_LISTINGS_SUCCESS"
export const FETCH_MY_LISTINGS_FAIL = "FETCH_MY_LISTINGS_FAIL"
export const FETCH_MY_RECENT_LISTINGS_SUCCESS = "FETCH_MY_RECENT_LISTINGS_SUCCESS"
export const FETCH_MY_RECENT_LISTINGS_FAIL = "FETCH_MY_RECENT_LISTINGS_FAIL"
export const FETCH_MY_LISTING_DETAIL_VIEW_SUCCESS = "FETCH_MY_LISTING_DETAIL_VIEW_SUCCESS"
export const FETCH_MY_LISTING_DETAIL_VIEW_FAIL = "FETCH_MY_LISTING_DETAIL_VIEW_FAIL"
export const CREATE_LISTINGS_SUCCESS = "CREATE_LISTINGS_SUCCESS"
export const CREATE_LISTINGS_FAIL = "CREATE_LISTINGS_FAIL"
export const REMOVE_MESSAGES_SUCCESS = "REMOVE_MESSAGES_SUCCESS"


// Analytics
export const FETCH_DASHBOARD_ANALTYICS_SUCCESS = "FETCH_DASHBOARD_ANALTYICS_SUCCESS"
export const FETCH_DASHBOARD_ANALTYICS_FAIL = "FETCH_DASHBOARD_ANALTYICS_FAIL"