export const APPLY_FOR_LISTING_SUCCESS = 'APPLY_FOR_LISTING_SUCCESS'
export const APPLY_FOR_LISTING_FAIL = 'APPLY_FOR_LISTING_FAIL'
export const HIRED_FOR_LISTING_SUCCESS = 'HIRED_FOR_LISTING_SUCCESS'
export const HIRED_FOR_LISTING_FAIL = 'HIRED_FOR_LISTING_FAIL'
export const UPDATE_APPLICATION_SUCCESS = 'UPDATE_APPLICATION_SUCCESS'
export const UPDATE_APPLICATION_FAIL = 'UPDATE_APPLICATION_FAIL'
export const DELETE_LISTINGS_SUCCESS = 'DELETE_LISTINGS_SUCCESS'
export const DELETE_LISTINGS_FAIL = 'DELETE_LISTINGS_FAIL'

// Analytics
export const DETAIL_VIEW_LISTINGS_SUCCESS = 'DETAIL_VIEW_LISTINGS_SUCCESS'
export const DETAIL_VIEW_LISTINGS_FAIL = 'DETAIL_VIEW_LISTINGS_FAIL'

export const REMOVE_MESSAGES = 'REMOVE_MESSAGES'