export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL"
export const CREATE_CHAT_ROOM_SUCCESS = "CREATE_CHAT_ROOM_SUCCESS"
export const CREATE_CHAT_ROOM_FAIL = "CREATE_CHAT_ROOM_FAIL"
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS"
export const FETCH_MESSAGE_FAIL = "FETCH_MESSAGE_FAIL"
export const FETCH_CHAT_ROOMS_SUCCESS = "FETCH_CHAT_ROOMS_SUCCESS"
export const FETCH_CHAT_ROOMS_FAIL = "FETCH_CHAT_ROOMS_FAIL"


export const CLEAR_CHAT_ROOM_ID = "CLEAR_CHAT_ROOM_ID"