export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL"
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS"
export const FETCH_MESSAGE_FAIL = "FETCH_MESSAGE_FAIL"