export const FETCH_LISTINGS_SUCCESS = "FETCH_LISTINGS_SUCCESS"
export const FETCH_LISTINGS_FAIL = "FETCH_LISTINGS_FAIL"
export const FETCH_DETAIL_LISTING_VIEW_SUCCESS = "FETCH_DETAIL_LISTING_VIEW_SUCCESS"
export const FETCH_DETAIL_LISTING_VIEW_FAIL = "FETCH_DETAIL_LISTING_VIEW_FAIL"

export const REMOVE_MESSAGES = "REMOVE_MESSAGES"